version: '3'

services:
  erddap:
    container_name: erddap
    image: axiom/docker-erddap:2.18
    restart: unless-stopped
    hostname: dummy-erddap
    ports:
      - 8080:8080
    volumes:
      - ./conf:/usr/local/tomcat/content/erddap
      - ./erddapData:/erddapData   # bind mount for ERDDAP internal data
      - ./datasets:/datasets # bind mount for user data files
      - /home/enoc/workspace/erddap-playground/conf/custom_logo.png:/usr/local/tomcat/webapps/erddap/images/obsea_logo_blanc.png
